/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <array>
#pragma once

/**
 * ! Do not edit this file directly !
 *
 * Generated automatically from fwk_only_metadata_tags.mako. To be included in libcameraservice
 * only by Camera3Device.cpp.
 */

namespace android {

/**
 * Framework only CaptureRequest keys. To be used for filtering out keys in CaptureRequest
 * before sending to the HAL.
 */
constexpr std::array kFwkOnlyMetadataKeys = {
        ANDROID_CONTROL_AF_REGIONS_SET,
        ANDROID_CONTROL_AE_REGIONS_SET,
        ANDROID_CONTROL_AWB_REGIONS_SET,
        ANDROID_CONTROL_ZOOM_METHOD,
        ANDROID_SCALER_CROP_REGION_SET,
};

} //namespace android
